# Generated by Django 5.1.4 on 2025-01-07 14:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('last_request_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('error_details', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
