# Generated by Django 5.1.4 on 2025-01-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='last_error_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlog',
            name='last_successful_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
